### PR TITLE
feat: Add custom hovertext for editor summary and project

### PR DESCRIPTION
**Pull request by johan-bjareholt**

### CODE REVIEW

**Comment by ErikBjare** [comment]
Looks like the rerun https://github.com/ActivityWatch/aw-webui/actions/runs/167785545 of [`bbff399` (#217)](https://github.com/ActivityWatch/aw-webui/pull/217/commits/bbff399739a911972f6033c430b21f6863dabd62) didn't have the same error as the original run but instead had the weird e2e/aw-client-js/axios thing we've seen before:

```
 My fixture
 ✖ Take a screenshot of the activity view

   1) A JavaScript error occurred on
      "http://localhost:27180/#/activity/erb-main2-arch".
      Repeat test actions in the browser and check the console for errors.
      If you see this error, it means that the tested website caused it.
      You can fix it or disable tracking JavaScript errors in TestCafe. To
      do the latter, enable the "--skip-js-errors" option.
      If this error does not occur, please write a new issue at:

   "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".

      JavaScript error details:
      Error: Module build failed: Error: ENOENT: no such file or
      directory, open

   '/home/runner/work/aw-webui/aw-webui/aw-client-js/node_modules/axios/index.js'
```

**Comment by ErikBjare** [comment]
I see now that:

```
Error: Command failed: xvfb-run --server-args="-screen 0 1280x720x24" npx testcafe chrome test/e2e/
```

Note the screen size.

And the error happens on:

```
          5 |test('Take a screenshot of the activity view', async t => {
          6 |  const width = 1280;
          7 |  const height = 800;
          8 |  await t
          9 |    // For resizeWindow to work tests needs to run with a
      ICCCM/EWMH-compliant window manager
       > 10 |    .resizeWindow(width, height)
         11 |    .click('#load-demo')
         12 |    // TODO: Figure out how to click all hide-devonly buttons
      instead of hardcoding number of clicks
         13 |    .click('.hide-devonly')
         14 |    .click('.hide-devonly');
         15 |
```

Where the screen size is larger than the one set up by xvfb.

In another passing build I found the warning:

```
 Warnings (1):
 --
  Was unable to resize the window due to an error.

  The
  /home/runner/work/aw-webui/aw-webui/node_modules/testcafe-browser-tools/bin/linux/glibc-64/resize
  process failed with the null exit code.
```

So we should probably fix that.

**Comment by ErikBjare** [comment]
Once https://github.com/ActivityWatch/aw-webui/pull/221 is merged you can rebase on master, drop the `--force` commit, and it should work.

**Comment by johan-bjareholt** [comment]
@ErikBjare Nice, seems to work! :smile:

**Pull request merged**
