### PR TITLE
Added the html5 dateselector to activity view

### PR DESCRIPTION
**Pull request by johan-bjareholt**

### CODE REVIEW

**Comment by ErikBjare** [comment]
LGTM!

**Comment by ErikBjare** [comment]
Noticed that the styling wasn't quite right, so fixed that in https://github.com/ActivityWatch/aw-webui/commit/afeed4a3189d64eaa0fa2846c6e0891f0e80e44c

**Comment by ErikBjare** [comment]
Yeah, I had some issues keeping the refresh button to the right, and eventually gave up because it wasn't worth my time. Same with the width of the dateselector really, perhaps I should just have set the width using rem measurements.

**Comment by johan-bjareholt** [comment]
Should work properly now https://github.com/ActivityWatch/aw-webui/commit/17b82989e7759107fe9e291784203bf0b5644251

**Comment by ErikBjare** [comment]
@johan-bjareholt Woah, nice. Haven't learned all this new Bootstrap 4 stuff yet.

**Comment by johan-bjareholt** [comment]
@ErikBjare Me neither, took a while to get right. In the end I used flexbox however which was supported pre-bootstrap4 I believe, I didn't have any previous experience with that either though.

**Pull request merged**
