### PR TITLE
Migrating to Vue 2.0

### PR DESCRIPTION
**Pull request by ErikBjare**
Very much work-in-progress. Change merge base to `master` when `dev/timeline` is merged.

Issues:

 - [x] Warnings relating to v-for when running `npm run dev`
 - [x] Only view loads, not the menus etc. Probably a router issue.
 - [x] vue-strap stuff likely broken (all the accordions and some minor things) since it lacks support for Vue 2.0, consider using [bootstrap-vue](https://github.com/bootstrap-vue/bootstrap-vue) instead (has barely existed for half a year, but looks good and is active). **Edit:** Apparently there is a [fork of vue-strap](https://wffranco.github.io/vue-strap/) that's supposed to support Vue 2.1+.

### CODE REVIEW

**Comment by ErikBjare** [comment]
Related issue: #11

**Comment by ErikBjare** [comment]
This should probably have higher priority as it will only get harder as time progresses.

**Comment by johan-bjareholt** [comment]
@ErikBjare 

Home and Activity views now work in vue2, bootstrap for view is still not fixed though so the buckets view is still broken

**Comment by ErikBjare** [comment]
Great! 

Nice work :smile:

**Comment by johan-bjareholt** [comment]
Since bootstrap4 does not include glyphicons anymore I sat for a long time and tried to install vue-awesome without any success. I gave up and instead worked on upgrading to webpack2, and then suddenly it started to work... Damn javascript and it's bleeding edge hipster library developers not specifying that webpack2 was required.

**Comment by johan-bjareholt** [comment]
Left to do

- [ ] Fix broken icon padding
- [ ] Add icons and pimp bucket view

**Comment by johan-bjareholt** [comment]
Should be ready for merging, would like a review first though since it's a quite large changeset.

**Comment by johan-bjareholt** [comment]
To me it even looks better than it did previously now

**Comment by ErikBjare** [comment]
Ready to merge @johan-bjareholt?

**Comment by johan-bjareholt** [comment]
I think it's ready for merging yes, has been working nicely for me the last few days.

Have you read through it, or atleast skimmed through? Give an approve and I'll merge.

**Comment by ErikBjare** [comment]
Apparently I can't review and approve a PR I created myself. Skimmed it previously, looked good to me.

**Pull request merged**
