### PR TITLE
fix: fix category name change affecting sister category (ActivityWatch/activitywatch#361)

### PR DESCRIPTION
**Pull request by billangli**
The following changes address this issue: https://github.com/ActivityWatch/activitywatch/issues/361. 
* Use category ID to identify categories
* Delete category is moved from the edit modal to be its own button, it also has a confirmation modal now
* Delete category also deletes all descendents of that category (i.e. deletes its subtree)
* In the edit modal, it will no longer show categories in that category's subtree as its potential parent

Here are the new UI changes: 
Screenshot from 2021-01-09 20-06-00
Screenshot from 2021-01-09 20-06-14

The following code changes also allow two categories with the same path and name (e.g. Work -> Programming and Work -> Programming). I was originally thinking that I would have to change the backend to support this change. However, we don't have to change the backend if we disallow these duplicates. Then the web app can still query categories by using its full name (e.g. `['Work', 'Programming']`). Let me know if you think of any other solutions.

Edit: It is failing two tests because I removed the code from `build_category_hierarchy` that fills in missing parents. This is because before this change, each category's name (e.g. `['Work', 'Programming', 'ActivityWatch']`) already stores information about all of its parents, so you can keep only this information in storage and generate the parent categories Work and Work -> Programming. But now each category only keeps a reference to its immediate parent or children, which is why we can no longer generate parents. 

**Edit 2: I'm starting to think that an easier solution is to require all full names are unique and it would not need use ID, it would resolve the problems that I mentioned in the two paragraphs above.**

### CODE REVIEW

**Comment by johan-bjareholt** [comment]
Two tests regarding classes seem to be failing, either there is some bug or the tests need to be fixed.

**Comment by johan-bjareholt** [comment]
> Edit 2: I'm starting to think that an easier solution is to require all full names are unique and it would not need use ID, it would resolve the problems that I mentioned in the two paragraphs above.

Yes, I think this is better. The case you mentioned before with allowing two categories with the same name and parent ("Work -> Programming" and "Work -> Programming") doesn't seem like a real use-case. The important thing to fix is that for example two categories with the same name but different parent doesn't clash.

**Comment by ErikBjare** [comment]
Sorry for the late review.

>I'm starting to think that an easier solution is to require all full names are unique and it would not need use ID

I'm leaning towards this too. 

I have a few questions about the diff, but those comments probably wouldn't be relevant if we did it this way anyway. (one of the concerns was how updating AW will affect existing instances where the `parentId`'s are missing)

I think simply changing the 'New category' button behavior to open the 'edit category' modal directly would resolve the issue (as described in https://github.com/ActivityWatch/activitywatch/issues/361#issuecomment-596180857).

---

And regarding moving the 'delete category' button, the previous UI of hiding it in the edit modal was very intentional (due to limited space on small screens, like on mobile), so I think it should be reverted.

**Comment by billangli** [comment]
Thanks for the review, guys. Here is what I'll change:

- Show 'edit category' whenever a new category is created
- Make sure the full names (including ancestors) are unique
- Keep the old delete button (I do agree that it is crowded)

**Pull request closed without merging**
