### PR TITLE
Ran eslint --fix on everything

### PR DESCRIPTION
**Pull request by ErikBjare**
I noticed when creating #176 that we weren't using prettier. This fixes that.

### CODE REVIEW

**Comment by johan-bjareholt** [comment]
Have you manually tested this?

Last time I tried running "eslint --fix" the webui was broken in a few places so I never submitted it.

**Comment by ErikBjare** [comment]
I haven't, but I will first be merging #176 and then rerunning this and go through the entire diff before merging.

**Comment by ErikBjare** [comment]
Merged #176 (still needs good demo data, but works), reset this branch to master, re-ran `make lint-fix`, and everything seems to be working (I couldn't test web or editor activity, but nothing else was broken). 

Will be going through the diff and then merge when CI passes.

**Comment by ErikBjare** [comment]
Diff looks fine. Merging.

**Pull request merged**
