### PR TITLE
Redesign header

### PR DESCRIPTION
**Pull request by johan-bjareholt**
Based on the settings PR

aw-new-header

### CODE REVIEW

**Comment by ErikBjare** [comment]
Ooooh, that looks super nice! 😍

How does it look on mobile though? Would be really nice to get it looking good on mobile as well.

**Comment by johan-bjareholt** [comment]
I spent a lot of time getting it to work nicely on mobile first but bootstrap/CSS is a pain in the ass so I never really got it working properly. Rewrote it cleanly for desktop-only and here's the result. Will give it another try later.

**Comment by ErikBjare** [comment]
I could fix it if you don't mind? I've gotten decent at Bootstrap by now.

**Comment by johan-bjareholt** [comment]
Sure, go ahead.

**Comment by ErikBjare** [comment]
Done!

image

image

There are many other styling issues on mobile, but this is a great start.

**Comment by ErikBjare** [comment]
Some final improvements:

image

**Comment by johan-bjareholt** [comment]
Just need to rebase on master and remove the top 2 commits before merging.

**Pull request merged**
