### PR TITLE
fix: fixes issue with migrating category settings to the server

### PR DESCRIPTION
**Pull request by ErikBjare**
Fixes https://github.com/ActivityWatch/activitywatch/issues/1067

Analysis of the issue in https://github.com/ActivityWatch/activitywatch/issues/1067#issuecomment-2150693674

### CODE REVIEW

**Review by BelKed — APPROVED** [review]
Manually verified, works as intended. The error doesn't show up in the UI and the data is displayed normally :)

**Comment by ErikBjare** [comment]
@BelKed Did you check the codepath by reproducing the error? (possibly by removing the entry in the server-side settings)

**Comment by BelKed** [comment]
> @BelKed Did you check the codepath by reproducing the error? (possibly by removing the entry in the server-side settings)

Yes, exactly:
1. Removed the `classes` entry from the database.
2. Added an empty `classes` entry to the `localStorage` (`localStorage.setItem("classes", "")`)
3. The error doesn't appear anymore :)

**Comment by ErikBjare** [comment]
Awesome, triggering a build for v0.13.1 now.

**Pull request merged**
