### PR TITLE
Made activity view categorized by tabs and added top URL summary

### PR DESCRIPTION
**Pull request by johan-bjareholt**
Made activity view tabbed.

We need some way to hide stuff such as editors which will not be used by everyone since the page will otherwise be very long, but not sure if this is the perfect solution.

screenshot-2018-6-17 activitywatch

### CODE REVIEW

**Comment by ErikBjare** [comment]
Looks pretty good, should probably make the tabs stand out more though because I didn't see them at first.

**Comment by johan-bjareholt** [comment]
screenshot-2018-6-18 activitywatch
There, they should be more clear now!
Required some custom CSS sadly.

**Comment by Otto-AA** [comment]
Looks good :+1: 

If it's not too much coding effort, I think it would be awesome if one could choose which data is displayed in the summary. For instance, that it displays "Top coding Projects" instead of "Top window Titles".

**Comment by johan-bjareholt** [comment]
Nice idea!

However that would be quite a bit of work due to the website currently being stateless, this would require us to save these settings somehow (probably either in the backend or in a cookie).
Personalization is probably what would make the user interface "great" instead of "good" though, so we will have to implement that eventually.

**Pull request merged**
