### PR TITLE
Integrate eslint and prettier

### PR DESCRIPTION
**Pull request by ianobermiller**
Integrate eslint and prettier with a pre-commit hook. I tried to choose defaults that matched the code style as closely as possible. Second commit applies the eslint fixes (which include prettier) to all the code.

You can run it yourself with 👍 
```
npm run lint
# or in watch mode
watch --color npm run lint --color
```

Test plan:
- npm run dev
- http://localhost:27180/#/ (make sure server is running in testing mode)

### CODE REVIEW

**Comment by ErikBjare** [comment]
Looks good! Does everything still work as intended?

**Comment by ErikBjare** [comment]
Looks like a bunch of changes became conflicted after merging this PR: https://github.com/ActivityWatch/aw-webui/pull/56

Fix them and I'll merge.

**Comment by johan-bjareholt** [comment]
Looks good, merging :)

**Comment by johan-bjareholt** [comment]
I am very confused. The last commit seems to have removed some code which was not visible inside this pull request diff?

I am working on my own PR now and trying to fix the merge conflicts, but I now see that multiple lines of code are reverted here. An example is all references to aw-summary in Activity.vue has been replaced with the old 'div#appsummary-container' notation as if it were using the old APIs?

By looking at the diff here in the PR everything seems fine, but comparing them file-by-file between these two commits shows multiple issues which break aw-webui completely.

Example:
First working commit: https://github.com/ActivityWatch/aw-webui/blob/9b527247049c1539a4f392031e2587d0055f2216/src/views/Activity.vue
Second broken commit: https://github.com/ActivityWatch/aw-webui/blob/653b212345740d6cb6acff73ec845e9bbad6d38b/src/views/Activity.vue

I have no idea how this occured, but I really need to sleep now. Likely something fishy when you did the rebase.

**Comment by johan-bjareholt** [comment]
Sorry but I have to revert this PR due to it "quietly" reverting code from #56. Even if I simply only reverted the Activity.vue file specifically it seems like eslint changed name of the visualization components as well as a few other things which makes this very hard and confusing to fix after these commits were applied.

**Comment by ianobermiller** [comment]
Weird, sorry it happened that way!

**Comment by johan-bjareholt** [comment]
It's ok, such a thing can happen to anyone. Still confused about how that could even happen though, very odd. It's a shame since it seemed like nice commits otherwise.

**Pull request merged**
