### PR TITLE
chore: remove broken api browser link

### PR DESCRIPTION
**Pull request by brayo-pip**
> [!IMPORTANT]
> Remove broken "API Browser" link from `Home.vue`.
> 
>   - **Behavior**:
>     - Removed broken "API Browser" link from `Home.vue` under the Resources section.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=ActivityWatch%2Faw-webui&utm_source=github&utm_medium=referral)<sup> for 89909b2e0f6b465ebc76d568ad188481d12eae4e. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Comment by ErikBjare** [comment]
Only broken in aw-server-rust, works fine for aw-server-python.

**Comment by brayo-pip** [comment]
I figured most people are running the rust server. I can just wrap in it in a `v-if` block to display only on python server.

**Comment by ErikBjare** [comment]
Sounds good!

**Comment by 0xbrayo** [comment]
@ErikBjare ping

**Pull request closed without merging**
