### PR TITLE
feat: progress on audible-as-active

### PR DESCRIPTION
**Pull request by ErikBjare**
I just banged this out without testing it at all, not sure if it'll work.

**Edit:** Huh, it wasn't too stupid after all. Seems to work...

Also re-adds the 'filter AFK' option.

Replaces #85 

Partially fixes https://github.com/ActivityWatch/activitywatch/issues/261

### Things to fix

 - [x] Prettier checkboxes at the bottom of the activity page
 - [x] More extensive testing?

### CODE REVIEW

**Review by johan-bjareholt — APPROVED** [review]
Surprised that it was this clean to implement, can't really see any flaws. Looks good!

**Comment by ErikBjare** [comment]
Did a bit more testing, seems to work fine. Merging when CI passes.

**Comment by johan-bjareholt** [comment]
@ErikBjare Not working with aw-server-rust, there was one query method missing (forgotten which one, noticed a few days ago).

I think it should be pretty easy to fix though.

**Comment by ErikBjare** [comment]
I assume it's period_union?

**Comment by dtgay** [comment]
Seems like this feature doesn't work on Brave due to https://github.com/ActivityWatch/activitywatch/issues/461. Can anyone else confirm?

The tab activity _is_ being marked as audible, but I think since the browser watcher isn't working it fails to qualify for the AFK exception.

Looks like https://github.com/ActivityWatch/aw-webui/pull/375 might be a workaround but doesn't appear available in latest (0.12.1).

**Pull request merged**
