### PR TITLE
Added setting for 'show last' duration default value

### PR DESCRIPTION
**Pull request by riscie**
Regarding issue #338 https://github.com/ActivityWatch/activitywatch/issues/338

### CODE REVIEW

**Comment by ErikBjare** [comment]
Looks great! 

Just one thing: the TimePeriodInput component is intended to be used in other places as well, where the setting should not be applied. I believe the proper way to handle that is to make the initial value an optional component prop (basically an argument) that is passed from the timeline view.

If you could fix that, that'd be great. If you don't know how props and stuff work, just let me know and I'll fix it shortly 👌

**Comment by riscie** [comment]
I'll have a look :+1: (I'm an angular dev myself, so bare with me if this does not turn out as planned ^.^)

**Comment by riscie** [comment]
I've updated the pr with what I think is what you were suggesting. Let me know if this works for you.

**Comment by ErikBjare** [comment]
Excellent, that is exactly what I had in mind! Merging.

**Pull request merged**
