### PR TITLE
feat: added ability to edit events from timeline view

### PR DESCRIPTION
**Pull request by ErikBjare**
Requires the following to fetch single events by ID (needed for editing events cut off by query):

 - [x] https://github.com/ActivityWatch/aw-core/pull/109
 - [x] https://github.com/ActivityWatch/aw-server/pull/90
 - [x] https://github.com/ActivityWatch/aw-server-rust/pull/268
 - [x] https://github.com/ActivityWatch/aw-client/commit/32c25fd5a7b6cf78cb06256ee9394eac758128a1
 - [x] https://github.com/ActivityWatch/aw-client-js/pull/36

### CODE REVIEW

**Comment by johan-bjareholt** [comment]
Can this be an issue when editing events at the end/start of the current start time/endtime. Not sure if it applies to both aw-server-python and aw-server-rust, but I'm quite certain that it at least applies for aw-server-rust since it cuts the starttime or duration if it is outside starttime or endtime to give more accurate results.

**Comment by johan-bjareholt** [comment]
That's also the reason why we didn't end up adding support for editing in the search view.

**Comment by ErikBjare** [comment]
@johan-bjareholt Ah, yeah that's right. I'll look into a way to get the full event to be edited.

**Comment by ErikBjare** [comment]
@johan-bjareholt I've now added a API to aw-server and aw-server-rust to fetch a single event by its ID, and will use that to fetch the full event to be edited.

**Pull request merged**
